graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: true

graphiql:
  mapping: /graphiql
  endpoint: /graphql
  enabled: true

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/milklabdb
    username: postgres
    password: 236081273
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
server:
  port: 5000

#logging:
#  level:
#    root: DEBUG

config:
  secret: "MilklabApplicationSecret"
  expiration: 604800 # day
  prefix: "Bearer "
  header: "Authorization"